version: '3.8'

services:
  systemconfig-service:
    build: .
    container_name: systemconfig-service
    ports:
      - "8085:8085"
    environment:
      - JAVA_OPTS=-Xmx1G -XX:+UseG1GC
    depends_on:
      - postgres
    networks:
      - galphos-network
    restart: unless-stopped
    volumes:
      - ./server_config.json:/app/server_config.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/api/system/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  postgres:
    image: postgres:13
    container_name: systemconfig-postgres
    environment:
      POSTGRES_DB: systemconfig_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"  # 使用不同端口避免冲突
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
    networks:
      - galphos-network
    restart: unless-stopped

networks:
  galphos-network:
    driver: bridge

volumes:
  postgres_data:
