version: '3.8'

services:
  submission-service:
    build: .
    ports:
      - "3004:3004"
    environment:
      - JVM_OPTS=-Xmx512m -Xms256m
    depends_on:
      - postgres
    networks:
      - galphos-network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: galphos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
    networks:
      - galphos-network

volumes:
  postgres_data:

networks:
  galphos-network:
    driver: bridge
