version: '3.8'

services:
  region-postgres:
    image: postgres:15
    container_name: region-postgres
    environment:
      POSTGRES_DB: region_management
      POSTGRES_USER: db
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - region_postgres_data:/var/lib/postgresql/data
      - ./init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
    networks:
      - galphos-network

  region-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: region-service
    ports:
      - "3007:3007"
    depends_on:
      - region-postgres
    environment:
      - JAVA_OPTS=-Xmx1g -Xms512m
    volumes:
      - ./server_config.json:/app/server_config.json
      - ./logs:/app/logs
    networks:
      - galphos-network

volumes:
  region_postgres_data:

networks:
  galphos-network:
    external: true
